# Configuration file for the discord-hvz bot, in YAML format. These settings only apply on program start.
# YAML Reference: https://camel.readthedocs.io/en/latest/yamlref.html

# The ID of the Discord server to connect to.
server_id: 767126786617114635

# The ID of the Google Sheet that the bot will send its data to.
# The ID can be found in the URL, like this: https://docs.google.com/spreadsheets/d/1YUXeRoEpV9MukZ7B_xVlBkc-D6DNEfVxLBmJlf1Fm-0/edit#gid=0
# In the URL above, the ID is 1YUXeRoEpV9MukZ7B_xVlBkc-D6DNEfVxLBmJlf1Fm-0
# The Google Account that the bot is logged into must have edit access to this sheet

sheet_id: 1fLYdmc_sp-Rx25794zmPekp48I02lbctyqiLvaLDIwQ

# The timezone the GAME is being played in. Surround in "quotes."
# It is best to set this to your location. Find the IANA database name for your location here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Alternatively, this can be an offset from UTC such as "-5". WARNING: This will not automatically account for seasonal time changes.
timezone: 'America/Chicago'

# Is registration enabled?
registration: true

# Is tag logging enabled on the server? Useful for making sure the game doesn't start too early.
tag_logging: true

# If true, the OZ's identity will not be included in tag announcements. 
silent_oz: false

# Will the database be automatically exported to a Google Sheet? Requires some setup.
# Turn this off if you're having trouble with Google Sheets
google_sheet_export: true

# The names of the sheets on the Google Sheet to use.

sheet_names:
  members: Members
  tags: Tags

# Assign the real channel names on the right to the variables on the left
# All are required except bot-output, which is optional.
channel_names:
  tag-announcements: tag-announcements
  report-tags: report-tags
  zombie-chat: zombie-chat
  bot-output: bot-output

# Assign the real role names on the right to the variables on the left
role_names:
  zombie: zombie
  human: human
  player: player

# The below lists define database tables. When the bot boots up, it will create any tables that don't exist.
# It WILL NOT edit existing tables to match this config. To add or subtract columns, the table or database must be deleted
# This config also defines the order the columns appear on the Google Sheet. Any unlisted columns will appear last
# Column order on the Sheet IS changeable without remaking the database or tables
# The following columns and tables are required and will appear in the database whether or not they are defined here.
# members: ID, Name, Faction, Tag_Code, OZ
# tags: Tag_ID, Tagger_ID, Tagger_Name
database_tables:
  members:
    id: Integer
    name: String
    nickname: String
    discord_name: String
    cpo: String
    faction: String
    tag_code: String
    oz_desire: String
    email: String
    want_bandana: String
    registration_time: DateTime
    oz: Boolean
  tags:
    tag_id: incrementing_integer
    tagger_id: Integer
    tagger_name: String
    tagger_nickname: String
    tagger_discord_name: String
    tagged_id: Integer
    tagged_name: String
    tagged_nickname: String
    tagged_discord_name: String
    tag_time: DateTime
    report_time: DateTime
    revoked_tag: String

# The path to the game database file. If it does not exist, the bot will create it.
# Regardless of which system you are on, use '/' forward slashes in the path.
# The bot will search for the file in the top directory: the one that contains config.yml, .env, etc.
# If the path is a file, it must end in '.db'
# If the path is a folder, the file "game_database.db" will be created inside it. Example: "my_database_folder"
# For a file in the top directory (default), use "name_of_my_database.db"
# For a file in a directory within the top directory, use "my_database_folder/my_database_name.db"
# To start your path at the root of the drive, start with a '/'. Example: "/Users/JohnDoe/Documents/discord-hvz/cool_database.db"
database_path: "game_database.db"

