# Configuration file for the discord-hvz bot, in YAML format. These settings only apply on program start.
# YAML Reference: https://camel.readthedocs.io/en/latest/yamlref.html

# The server for the bot to activate on. Only one at a time. Must be in available_servers
active_server: dev

# A dictionary of servers and their ids. 
available_servers:
  dev: 767126786617114635
  letu: 760568283723202630

#Is registration enabled?
registration: true

# Is tag logging enabled on the server? Useful for making sure the game doesn't start too early.
tag_logging: true

# If true, the OZ's identity will not be included in tag announcements. 
silent_oz: false

# The IDs of the Google Sheets that the bot will send its data to.
# The ID can be found in the URL, like this: https://docs.google.com/spreadsheets/d/1YUXeRoEpV9MukZ7B_xVlBkc-D6DNEfVxLBmJlf1Fm-0/edit#gid=0
# It's the long string of characters near the end.
# The Google Account that the bot is logged into must have edit access to this sheet
# These sheets will be chosen based on the active_server selected above
sheet_ids:
  letu: 1q-2H32CRpIDCbP94rBPbIKwGSJ-dHDZjL9SCHCUAaPo
  dev: 1fLYdmc_sp-Rx25794zmPekp48I02lbctyqiLvaLDIwQ

sheet_settings:
  members:
    sheet_name: Members
    column_order:
    - ID
    - Name
    - Nickname
    - Discord_Name
    - Faction
    - CPO
    - Tag_Code
    - OZ_Desire
    - Email
    - Want_Bandana
    - Registration_Time
    - OZ
  tags:
    sheet_name: Tags
    column_order:
    - Tag_ID
    - Tagger_ID
    - Tagger_Name
    - Tagger_Nickname
    - Tagger_Discord_Name
    - Tagged_ID
    - Tagged_Name
    - Tagged_Nickname
    - Tagged_Discord_Name
    - Tag_Time
    - Report_Time
    - Revoked_Tag

# Assign the real channel names on the right to the variables on the left
channel_names:
  tag-announcements: tag-announcements
  report-tags: report-tags
  landing: hvz-first-things-first
  zombie-chat: zombie-chat


