# Configuration file for the discord-hvz bot, in YAML format. These settings only apply on program start.
# YAML Reference: https://camel.readthedocs.io/en/latest/yamlref.html

# The server for the bot to activate on. Only one at a time. Must be in available_servers
active_server: dev

# A dictionary of servers and their ids. 
available_servers:
  dev: 767126786617114635
  letu: 760568283723202630

#Is registration enabled?
registration: true

# Is tag logging enabled on the server? Useful for making sure the game doesn't start too early.
tag_logging: true

# If true, the OZ's identity will not be included in tag announcements. 
silent_oz: false

# The IDs of the Google Sheets that the bot will send its data to.
# The ID can be found in the URL, like this: https://docs.google.com/spreadsheets/d/1YUXeRoEpV9MukZ7B_xVlBkc-D6DNEfVxLBmJlf1Fm-0/edit#gid=0
# It's the long string of characters near the end.
# The Google Account that the bot is logged into must have edit access to this sheet
# These sheets will be chosen based on the active_server selected above
sheet_ids:
  letu: 1H8dlyi1xj3jCP7-TrMCPGcfuDQ-LAHq1BmyrFORpCA8
  dev: 1fLYdmc_sp-Rx25794zmPekp48I02lbctyqiLvaLDIwQ

sheet_settings:
  members:
    sheet_name: Members
    column_order:
    - ID
    - Name
    - Nickname
    - Discord_Name
    - Faction
    - CPO
    - Tag_Code
    - OZ_Desire
    - Email
    - Want_Bandana
    - Registration_Time
    - OZ
  tags:
    sheet_name: Tags
    column_order:
    - Tag_ID
    - Tagger_ID
    - Tagger_Name
    - Tagger_Nickname
    - Tagger_Discord_Name
    - Tagged_ID
    - Tagged_Name
    - Tagged_Nickname
    - Tagged_Discord_Name
    - Tag_Time
    - Report_Time
    - Revoked_Tag

# The below lists define database tables. When the bot boots up, it will create any tables that don't exist.
# It WILL NOT edit existing tables to match this config. To add or subtract columns, the table or database must be deleted
# This config also defines the order the columns appear on the Google Sheet. Any unlisted columns will appear last
# Column order on the Sheet IS changeable without remaking the database or tables
# The following columns and tables are required and will appear in the database whether or not they are defined here.
# members: ID, Name, Faction, Tag_Code, OZ
# tags: Tag_ID, Tagger_ID, Tagger_Name
database_tables:
  members:
    ID: String
    Name: String
    Nickname: String
    Discord_Name: String
    CPO: String
    Faction: String
    Tag_Code: String
    OZ_Desire: String
    Email: String
    Want_Bandana: String
    Registration_Time: DateTime
    OZ: Boolean
  tags:
    Tag_ID: Integer
    Tagger_ID: String
    Tagger_Name: String
    Tagger_Nickname: String
    Tagger_Discord_Name: String
    Tagged_ID: String
    Tagged_Name: String
    Tagged_Nickname: String
    Tagged_Discord_Name: String
    Tag_Time: DateTime
    Report_Time: DateTime
    Revoked_Tag: String

# Assign the real channel names on the right to the variables on the left
channel_names:
  tag-announcements: tag-announcements
  report-tags: report-tags
  landing: hvz-first-things-first
  zombie-chat: zombie-chat
  bot-output: bot-output

# Valid button colors: blurple, gray, green, red, url
# Buttons must match the names of the functions they call
buttons:
  register:
    message: "Use the button below and check your Direct Messages to register for HvZ!"
    label: "Register for HvZ"
    color: green
  tag_log:
    message: "Use the button below and check your Direct Messages to log a tag."
    label: "Log Tag"
    color: green


